<a href="https://colab.research.google.com/github/vhousos/EKPA/blob/main/Diabetes_vhousos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
data = pd.read_csv('https://raw.githubusercontent.com/kdemertzis/EKPA/main/Data/phishing_dataset.csv', delimiter=',')

In [2]:
data = data.sample(frac=1).reset_index(drop=True)
data.head()

Domain  Have_IP  Have_At  URL_Length  URL_Depth  \
0       blog.directsupply.com        0        0           1          0   
1                 twitter.com        0        0           1          1   
2  passiontoprofitclients.com        0        0           1          8   
3                veazieit.com        0        0           1          3   
4                vmoremlm.com        0        0           1          3   

   Redirection  https_Domain  TinyURL  Prefix/Suffix  DNS_Record  Web_Traffic  \
0            0             0        0              0           0            0   
1            0             0        0              0           0            1   
2            0             0        0              0           0            1   
3            0             0        1              0           0            1   
4            0             0        0              0           0            1   

   Domain_Age  Domain_End  iFrame  Mouse_Over  Right_Click  Web_Forwards  \
0           0           1       1           1            1             1   
1           1           1       0           0            1             0   
2           1           1       1           0            1             0   
3           0           0       0           0            1             0   
4           0           1       0           0            1             0   

   Label  
0      1  
1      0  
2      1  
3      1  
4      1

In [3]:
X = data.drop(['Domain', 'Label'], axis=1)

In [4]:
X.head()

Have_IP  Have_At  URL_Length  URL_Depth  Redirection  https_Domain  \
0        0        0           1          0            0             0   
1        0        0           1          1            0             0   
2        0        0           1          8            0             0   
3        0        0           1          3            0             0   
4        0        0           1          3            0             0   

   TinyURL  Prefix/Suffix  DNS_Record  Web_Traffic  Domain_Age  Domain_End  \
0        0              0           0            0           0           1   
1        0              0           0            1           1           1   
2        0              0           0            1           1           1   
3        1              0           0            1           0           0   
4        0              0           0            1           0           1   

   iFrame  Mouse_Over  Right_Click  Web_Forwards  
0       1           1            1             1  
1       0           0            1             0  
2       1           0            1             0  
3       0           0            1             0  
4       0           0            1             0

In [6]:
y=np.ravel(data['Label'])
#y=np.ravel(data['Outcome'])

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=43)

In [8]:
# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
# Define classifiers
classifiers = [
    LogisticRegression(),
    SVC(),
    RandomForestClassifier(),
    MLPClassifier(),
    KNeighborsClassifier(),
    DecisionTreeClassifier()
]

In [10]:
# Evaluate and compare classifiers
results = {'Classifier': [], 'Accuracy': [], 'Precision': [], 'Recall': [], 'F1 Score': []}

for clf in classifiers:
    clf_name = clf.__class__.__name__

    # Train the classifier
    clf.fit(X_train, y_train)

    # Make predictions
    y_pred = clf.predict(X_test)

    # Calculate evaluation metrics
    acc = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')

    # Confusion matrix
    cm = confusion_matrix(y_test, y_pred)

    # Display results
    print(f"\n{clf_name} Metrics:")
    print(f"Accuracy: {acc}")
    print(f"Precision: {precision}")
    print(f"Recall: {recall}")
    print(f"F1 Score: {f1}")
    print("Confusion Matrix:")
    print(cm)

    # Store results for comparison
    results['Classifier'].append(clf_name)
    results['Accuracy'].append(acc)
    results['Precision'].append(precision)
    results['Recall'].append(recall)
    results['F1 Score'].append(f1)


LogisticRegression Metrics:
Accuracy: 0.8096666666666666
Precision: 0.8358115287627558
Recall: 0.8096666666666666
F1 Score: 0.8056155306053471
Confusion Matrix:
[[1437   75]
 [ 496  992]]

SVC Metrics:
Accuracy: 0.8353333333333334
Precision: 0.8638948256828046
Recall: 0.8353333333333334
F1 Score: 0.8318119213496883
Confusion Matrix:
[[1476   36]
 [ 458 1030]]

RandomForestClassifier Metrics:
Accuracy: 0.8633333333333333
Precision: 0.8722445288478929
Recall: 0.8633333333333333
F1 Score: 0.8624097424551986
Confusion Matrix:
[[1424   88]
 [ 322 1166]]


/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(



MLPClassifier Metrics:
Accuracy: 0.844
Precision: 0.850452897557113
Recall: 0.844
F1 Score: 0.8431738909814354
Confusion Matrix:
[[1381  131]
 [ 337 1151]]

KNeighborsClassifier Metrics:
Accuracy: 0.8176666666666667
Precision: 0.8177433865292937
Recall: 0.8176666666666667
F1 Score: 0.8176387616021029
Confusion Matrix:
[[1252  260]
 [ 287 1201]]

DecisionTreeClassifier Metrics:
Accuracy: 0.8626666666666667
Precision: 0.8718783999999999
Recall: 0.8626666666666667
F1 Score: 0.8617078472742549
Confusion Matrix:
[[1425   87]
 [ 325 1163]]


In [11]:
# Display comparison results
results_df = pd.DataFrame(results)
results_df = results_df.sort_values(by='Accuracy', ascending=False)
print("\nComparison of Classifiers:")
print(results_df)


Comparison of Classifiers:
               Classifier  Accuracy  Precision    Recall  F1 Score
2  RandomForestClassifier  0.863333   0.872245  0.863333  0.862410
5  DecisionTreeClassifier  0.862667   0.871878  0.862667  0.861708
3           MLPClassifier  0.844000   0.850453  0.844000  0.843174
1                     SVC  0.835333   0.863895  0.835333  0.831812
4    KNeighborsClassifier  0.817667   0.817743  0.817667  0.817639
0      LogisticRegression  0.809667   0.835812  0.809667  0.805616
